/**
 * Ed25519 public key that auto-update manifests must be signed with (security
 * C2). Generated by scripts/gen-update-key.mjs, which rewrites the literal below;
 * the matching private key is the GitHub secret UPDATE_SIGNING_KEY.
 */
export const UPDATE_PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEALLNx13DOIYxpgLNZA97cR2Qe7+mLVaR0EhSNd9+f6sg=
-----END PUBLIC KEY-----`;
